### ISSUE TITLE
Java-Service: failed to start

### ISSUE THREAD

**Issue by VadzimN** [Feedmon/LCU-Challenge-Viewer#1]
The JSJS won't work on update 1.2.1, 1.3.0 or 1.3.1 for me. It loads for a few seconds and then updates the JS status to "failed to start".

**Comment by Feedmon** [comment]
Most likely it is because of an outdated java version on your computer. Does v1.1.0 work? If you haven't tried, try this and send me the console statement that is printed.

**Comment by VadzimN** [comment]
I had the latest version before and I've tried both the 32x and 64x bit.

![image](https://github.com/user-attachments/assets/7df3ce6d-5d5a-49c0-9a01-195f37696d70)

**Comment by Feedmon** [comment]
Yes this is a java version issue. If u type java -version in a cmd it should show >= 17
![grafik](https://github.com/user-attachments/assets/c645bf7f-f696-4ef1-b212-f279f5c2559d)

If you install java from "https://www.oracle.com/ch-de/java/technologies/downloads/#java21" it should work

**Comment by VadzimN** [comment]
It says "Java version "1.8.0_421", but I'll give the link a try. I'll write again in a second once the installation is complete.
![image](https://github.com/user-attachments/assets/53c6bf4a-859a-40f9-a50f-35c736ba42b6)
