### ISSUE TITLE
Images broken

### ISSUE THREAD

**Issue by furydude64** [Feedmon/LCU-Challenge-Viewer#2]
Every image that is after Ambessa is broken
![Screenshot 2024-11-10 064141](https://github.com/user-attachments/assets/3d75c1af-fedf-4fd2-9723-cf2f0ba543f7)

**Comment by Feedmon** [comment]
Does it fix itself when you go to one of the other views and then back to this one?

**Comment by furydude64** [comment]
No, that doesn't fix it. I also tried to reload challenge and eternal data, stopping client connection and reconnecting, turning league on and off and also tried restarting the app itself.

**Comment by Feedmon** [comment]
Looked into it. It has something to do with new champs in this case Ambessa. It should fix itself within 1 or 2 patches. Everything except icons and filtering by lanes should work normally tho.
